- name: RHEL - ADD $JAVA_HOME and $JRE_HOME environment variables
  lineinfile:
    path: "/etc/environment"
    line: "{{ item }}"
  with_items:
    # - "export JAVA_HOME=/usr/lib/jvm/jre-{{ openjdk_version }}-openjdk"
    - "export JRE_HOME=/usr/lib/jvm/jre/"
    - "export JAVA_HOME=/usr/java/jdk1.8.0_151/"
