---
# handlers file for ansible-jenkins

- name: enable_jenkins
  systemd:
    name: jenkins
    state: started
    enabled: True

- name: restart_jenkins
  systemd:
    name: jenkins
    state: restarted

